apiVersion: v1
kind: Service
metadata:
  name: biometric-identity-service
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  selector:
    app: biometric-identity
  ports:
    - name: grpc
      port: 80
      targetPort: grpc
    - name: http
      port: 90
      targetPort: http
