{{- if .Values.prometheus.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-alertmanager-ingress
  namespace: {{ default .Release.Namespace .Values.defaultNamespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  {{- if .Values.lumenvox.ingress.className }}
  ingressClassName: {{ .Values.lumenvox.ingress.className }}
  {{- end }}
  rules:
    - host: prometheus-alertmanager.{{ .Values.hostnameSuffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lumenvox-prometheus-alertmanager
                port:
                  number: 80
{{- end }}
