apiVersion: v1
kind: Service
metadata:
  name: admin-portal-service
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  selector:
    app: admin-portal
  ports:
    - name: portal
      port: 3001
      targetPort: portal
    - name: http
      port: 5110
      targetPort: http
