apiVersion: v1
kind: Service
metadata:
  name: archive-manager-service
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  selector:
    app: archive-manager
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3001
