apiVersion: v1
kind: Service
metadata:
  name: archive-service
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  selector:
    app: archive
  ports:
    - name: http
      port: 90
      targetPort: http
