apiVersion: v1
kind: Service
metadata:
  name: deployment-portal-service
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  selector:
    app: deployment-portal
  ports:
    - name: portal
      port: 3101
      targetPort: portal
    - name: http
      port: 5110
      targetPort: http
