apiVersion: v1
kind: Service
metadata:
  name: license-service
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  selector:
    app: license
  ports:
    - name: grpc
      port: 5000
      targetPort: grpc
    - name: http
      port: 5110
      targetPort: http
