apiVersion: v1
kind: Service
metadata:
  name: management-api-service
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  selector:
    app: management-api
  ports:
    - name: rest
      port: 81
      targetPort: rest
