apiVersion: v1
kind: Service
metadata:
  name: reporting-service
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  selector:
    app: reporting
  ports:
    - name: grpc
      port: 80
      targetPort: grpc
    - name: http
      port: 90
      targetPort: http
