apiVersion: v1
kind: Service
metadata:
  name: management-api-service
  namespace: {{ default .Release.Namespace .Values.defaultNamespace }}
spec:
  selector:
    app: management-api
  # type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
