{{/*apiVersion: v1*/}}
{{/*kind: Service*/}}
{{/*metadata:*/}}
{{/*  name: mongodb-service*/}}
{{/*  namespace: {{ default .Release.Namespace .Values.defaultNamespace }}*/}}
{{/*spec:*/}}
{{/*  selector:*/}}
{{/*    app: mongodb*/}}
{{/*  ports:*/}}
{{/*    - protocol: TCP*/}}
{{/*      port: 27017*/}}
{{/*      targetPort: 27017*/}}
