apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: license-list-deployments
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: list-deployments
subjects:
- kind: ServiceAccount
  name: license
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}