apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: list-deployments
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list