apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-portal-ingress
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  {{- if .Values.global.lumenvox.ingress.className }}
  ingressClassName: {{ .Values.global.lumenvox.ingress.className }}
  {{- end }}
  rules:
    - host: admin-portal.{{ .Values.global.hostnameSuffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-portal-service
                port:
                  name: portal
          {{- if .Values.global.lumenvox.metrics.enableEndpoints }}
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: admin-portal-service
                port:
                  name: http
          - path: /health  # Note this will override the admin portal native /health page
            pathType: Prefix
            backend:
              service:
                name: admin-portal-service
                port:
                  name: http
          - path: /alive
            pathType: Prefix
            backend:
              service:
                name: admin-portal-service
                port:
                  name: http
          - path: /ready
            pathType: Prefix
            backend:
              service:
                name: admin-portal-service
                port:
                  name: http
          {{- end }}
  tls:
    - secretName: speech-tls-secret
      hosts:
        - admin-portal.{{ .Values.global.hostnameSuffix }}
