apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: management-api-ingress
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  {{- if .Values.global.lumenvox.ingress.className }}
  ingressClassName: {{ .Values.global.lumenvox.ingress.className }}
  {{- end }}
  rules:
    - host: management-api.{{ .Values.global.hostnameSuffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: management-api-service
                port:
                  name: rest
  tls:
    - secretName: speech-tls-secret
      hosts:
        - management-api.{{ .Values.global.hostnameSuffix }}
