{{- if .Values.global.enableItn }}
{{- range .Values.global.asrLanguages }}
---
apiVersion: v1
kind: Service
metadata:
  name: itn-{{ .name | replace "_" "-" }}-service
  namespace: {{ default $.Release.Namespace $.Values.global.defaultNamespace }}
spec:
  selector:
    app: itn-{{ .name | replace "_" "-" }}
  ports:
    - name: grpc
      port: 80
      targetPort: grpc
    - name: http
      port: 90
      targetPort: http
{{- end }}
{{- end }}