apiVersion: v1
kind: Service
metadata:
  name: vad-service
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  selector:
    app: vad
  ports:
    - name: http
      port: 5110
      targetPort: http
