apiVersion: v2
name: lumenvox
description: LumenVox Helm chart for Kubernetes
type: application
version: 4.6.0
appVersion: "4.6.0"
home: https://lumenvox.com
annotations:
  artifacthub.io/containsSecurityUpdates: true
  artifacthub.io/images: |
    - name: cloud-init-tools
      image: lumenvox/cloud-init-tools:4.6

dependencies:
  - name: lumenvox-vb
    version: 4.6.0
    condition: global.enabled.lumenvoxVb
    repository: "https://lumenvox.github.io/helm-charts"

  - name: lumenvox-common
    version: 4.6.0
    condition: global.enabled.lumenvoxCommon
    repository: "https://lumenvox.github.io/helm-charts"

  - name: lumenvox-speech
    version: 4.6.0
    condition: global.enabled.lumenvoxSpeech
    repository: "https://lumenvox.github.io/helm-charts"

