apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reporting-bio-api-ingress
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  {{- if .Values.global.lumenvox.ingress.className }}
  ingressClassName: {{ .Values.global.lumenvox.ingress.className }}
  {{- end }}
  rules:
    - host: reporting-bio-api.{{ .Values.global.hostnameSuffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: reporting-bio-api-service
                port:
                  number: 80
