# Default values for speech.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: {}

global:
  asrLanguages: []
  ttsLanguages: []

asr:
  useFakeResult: "false"

tts:
  useFakeResult: "false"
