apiVersion: v2
name: lumenvox-common
description: LumenVox Common Components Helm chart for Kubernetes
type: application
version: 3.2.0
appVersion: "3.2.0"
home: https://lumenvox.com

dependencies:
  - name: "redis"
    condition: redis.enabled
    version: "15"
    repository: "https://charts.bitnami.com/bitnami"

  - name: "mongodb"
    condition: mongodb.enabled
    version: "10"
    repository: "https://charts.bitnami.com/bitnami"

  - name: "rabbitmq"
    condition: rabbitmq.enabled
    version: "8"
    repository: "https://charts.bitnami.com/bitnami"

  - name: "postgresql"
    condition: postgresql.enabled
    version: "10"
    repository: "https://charts.bitnami.com/bitnami"
