# Default values for lumenvox-common.

image: {}

global:
  deployments:
    affinity: {}
    nodeSelector: {}
    tolerations: []

lumenvox:
  # Time to allow support services (such as databases) to become available. Typically, 0 in production
  deploymentStartDelaySeconds: 0

encryption:
  masterKeyProvider: "EnvVariableMasterKeyService"
  useEncryption: true

linkerd:
  dashboard:
    # Applies ingress for linkerd dashboard when enabled (true)
    enabled: true
    # Namespace used by linkerd dashboard
    namespace: linkerd-viz
    # Hostname prefix to use for ingress
    hostPrefix: linkerd

  # optional class name to assign to linkerd ingress (i.e. "nginx" for example)
  ingressClassName: ""

prometheus: {}
