apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
  namespace: {{ default .Release.Namespace .Values.defaultNamespace }}
data:
  grafana.ini: |-
    # config file version
    apiVersion: 1

    # list of datasources that should be deleted from the database
    deleteDatasources:
      - name: Prometheus
        orgId: 1

    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-operated:9090
        # access: proxy
        access: direct
        isDefault: true
