apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-api
  namespace: {{ default .Release.Namespace .Values.defaultNamespace }}
  labels:
    app: management-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management-api
  template:
    metadata:
      labels:
        app: management-api
        # No Prometheus scraping for now
    spec:
      containers:
        - name: management-api
          image: {{ .Values.image.repository }}/cloud-management-api{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: web
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: {{ .Values.lumenvox.service.startDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          {{- if .Values.lumenvox.service.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: {{ .Values.lumenvox.service.startDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          {{- end }}
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 150m
              memory: 350Mi
          envFrom:
            - configMapRef:
                name: lumenvox-configmap
          env:
            - name: AETHER_ENV_SERVICE_START_DELAY_SECONDS
              value: '{{ .Values.lumenvox.service.startDelaySeconds }}'
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      initContainers:
        - name: wait-for-rabbitmq-service
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup {{ .Values.rabbitmq.connection.url }}; do echo waiting for RabbitMQ Service; sleep 2; done"]
          {{- if .Values.rabbitmq.init.checkManagementEndpoint }}
        - name: wait-for-rabbitmq-management-endpoint
          image: curlimages/curl:latest
          command: ["/bin/sh","-c"]
          args: ["while [ $(curl -sw '%{http_code}' http://{{ .Values.rabbitmq.connection.url }}:15672 -o /dev/null) -ne 200 ]; do sleep 2; echo 'Waiting for the RabbitMQ Management Page...'; done"]
          {{- end }}
