apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-verifier
  namespace: {{ default .Release.Namespace .Values.defaultNamespace }}
  labels:
    app: voice-verifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voice-verifier
  template:
    metadata:
      labels:
        app: voice-verifier
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '90'
        {{- if .Values.linkerd.enabled }}
        {{- if eq .Values.linkerd.ingressMode "nginx" }}
        linkerd.io/inject: enabled
        {{- else }}
        # Use traefik mode
        linkerd.io/inject: ingress
        {{- end }}
        {{- end }}
    spec:
      containers:
        - name: voice-verifier
          image: {{ .Values.image.repository }}/cloud-voice-verifier{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 90
            - name: grpc
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 90
            initialDelaySeconds: {{ .Values.lumenvox.service.startDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          {{- if .Values.lumenvox.service.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /health
              port: 90
            initialDelaySeconds: {{ .Values.lumenvox.service.startDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          {{- end }}
          resources:
            requests:
              cpu: 300m
              memory: 550Mi
            {{- if .Values.lumenvox.enforceLimits }}
            limits:
              cpu: 15000m
              memory: 1000Mi
            {{- end }}
          envFrom:
            - configMapRef:
                name: lumenvox-configmap
          env:
{{/*            - name: ConnectionStrings__PostgresConnection*/}}
{{/*              valueFrom:*/}}
{{/*                configMapKeyRef:*/}}
{{/*                  name: lumenvox-configmap*/}}
{{/*                  key: ConnectionStrings__PostgresConnection*/}}
{{/*            - name: ASPNETCORE_ENVIRONMENT*/}}
{{/*              valueFrom:*/}}
{{/*                configMapKeyRef:*/}}
{{/*                  name: lumenvox-configmap*/}}
{{/*                  key: ASPNETCORE_ENVIRONMENT*/}}
{{/*            - name: MOCK_TEST_DATA*/}}
{{/*              valueFrom:*/}}
{{/*                configMapKeyRef:*/}}
{{/*                  name: lumenvox-configmap*/}}
{{/*                  key: MOCK_TEST_DATA*/}}
{{/*            - name: ServiceAddresses__DeploymentService*/}}
{{/*              valueFrom:*/}}
{{/*                configMapKeyRef:*/}}
{{/*                  name: lumenvox-configmap*/}}
{{/*                  key: ServiceAddresses__DeploymentService*/}}
{{/*            - name: ServiceAddresses__VoiceVerifierService*/}}
{{/*              valueFrom:*/}}
{{/*                configMapKeyRef:*/}}
{{/*                  name: lumenvox-configmap*/}}
{{/*                  key: ServiceAddresses__VoiceVerifierService*/}}
{{/*            - name: ServiceAddresses__EngineResourceService*/}}
{{/*              valueFrom:*/}}
{{/*                configMapKeyRef:*/}}
{{/*                  name: lumenvox-configmap*/}}
{{/*                  key: ServiceAddresses__EngineResourceService*/}}
{{/*            - name: ServiceAddresses__ConfigurationService*/}}
{{/*              valueFrom:*/}}
{{/*                configMapKeyRef:*/}}
{{/*                  name: lumenvox-configmap*/}}
{{/*                  key: ServiceAddresses__ConfigurationService*/}}
{{/*            - name: ServiceAddresses__AssureVbs*/}}
{{/*              valueFrom:*/}}
{{/*                configMapKeyRef:*/}}
{{/*                  name: lumenvox-configmap*/}}
{{/*                  key: ServiceAddresses__AssureVbs*/}}
{{/*            - name: DOCKER_REGISTRY*/}}
{{/*              valueFrom:*/}}
{{/*                configMapKeyRef:*/}}
{{/*                  name: lumenvox-configmap*/}}
{{/*                  key: DOCKER_REGISTRY*/}}
{{/*            - name: DEPLOYMENT_POSTGRES_CONNECTION_STRING*/}}
{{/*              valueFrom:*/}}
{{/*                configMapKeyRef:*/}}
{{/*                  name: lumenvox-configmap*/}}
{{/*                  key: DEPLOYMENT_POSTGRES_CONNECTION_STRING*/}}
{{/*            - name: DASHBOARD_POSTGRES_CONNECTION_STRING*/}}
{{/*              valueFrom:*/}}
{{/*                configMapKeyRef:*/}}
{{/*                  name: lumenvox-configmap*/}}
{{/*                  key: DASHBOARD_POSTGRES_CONNECTION_STRING*/}}
            - name: ENGINE_RESOURCE_SERVICE_MAX_RECEIVE_SIZE
              value: '52428800'
            - name: SERVICE_START_DELAY_SECONDS
              value: '{{ .Values.lumenvox.service.startDelaySeconds }}'
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      initContainers:
        - name: wait-for-deployment-service
          image: curlimages/curl:latest
          command: ["/bin/sh","-c"]
          args: ["while [ $(curl -sw '%{http_code}' http://deployment-service.{{ default .Release.Namespace .Values.defaultNamespace }}:90/health -o /dev/null) -ne 200 ]; do sleep 2; echo 'Waiting for the Deployment Service...'; done"]
