apiVersion: apps/v1
kind: Deployment
metadata:
  name: assure-vbs
  namespace: {{ default .Release.Namespace .Values.defaultNamespace }}
  labels:
    app: assure-vbs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assure-vbs
  template:
    metadata:
      labels:
        app: assure-vbs
        # No Prometheus scraping for now
    spec:
      containers:
        - name: assure-vbs
          image: {{ .Values.image.repository }}/cloud-assure-vbs{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: web
              containerPort: 80
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /health*/}}
{{/*              port: 80*/}}
{{/*            initialDelaySeconds: 5*/}}
{{/*            periodSeconds: {{ .Values.probes.periodSeconds }}*/}}
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /health*/}}
{{/*              port: 80*/}}
{{/*            initialDelaySeconds: 10*/}}
{{/*            periodSeconds: {{ .Values.probes.periodSeconds }}*/}}
          resources:
            requests:
              cpu: 10m
              memory: 150Mi
            limits:
              cpu: 200m
              memory: 250Mi
          envFrom:
            - configMapRef:
                name: lumenvox-configmap

      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      initContainers:
        - name: wait-for-deployment-service
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup deployment-service.{{ default .Release.Namespace .Values.defaultNamespace }}; do echo waiting for Deployment Service; sleep 2; done"]
