apiVersion: apps/v1
kind: Deployment
metadata:
  name: assure-vbs
  namespace: {{ default .Release.Namespace .Values.defaultNamespace }}
  labels:
    app: assure-vbs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assure-vbs
  template:
    metadata:
      labels:
        app: assure-vbs
        # No Prometheus scraping for now
      annotations:
        {{- if .Values.linkerd.dashboard.ingressEnabled }}
        {{- if eq .Values.linkerd.dashboard.ingressMode "nginx" }}
        linkerd.io/inject: enabled
        {{- else }}
        # Default to traefik
        linkerd.io/inject: ingress
        {{- end }}
        {{- end }}
    spec:
      containers:
        - name: assure-vbs
          image: {{ .Values.image.repository }}/cloud-assure-vbs{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: web
              containerPort: 80
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /health*/}}
{{/*              port: 80*/}}
{{/*            initialDelaySeconds: 5*/}}
{{/*            periodSeconds: {{ .Values.probes.periodSeconds }}*/}}
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /health*/}}
{{/*              port: 80*/}}
{{/*            initialDelaySeconds: 10*/}}
{{/*            periodSeconds: {{ .Values.probes.periodSeconds }}*/}}
          resources:
            requests:
              cpu: 100m
              memory: 150Mi
            limits:
              cpu: 1500m
              memory: 800Mi
          envFrom:
            - configMapRef:
                name: lumenvox-configmap

      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      initContainers:
        - name: wait-for-deployment-service
          image: curlimages/curl:latest
          command: ["/bin/sh","-c"]
          args: ["while [ $(curl -sw '%{http_code}' http://deployment-service.{{ default .Release.Namespace .Values.defaultNamespace }}:90/health -o /dev/null) -ne 200 ]; do sleep 2; echo 'Waiting for the Deployment Service...'; done"]
