apiVersion: apps/v1
kind: Deployment
metadata:
  name: license
  namespace: {{ default .Release.Namespace .Values.defaultNamespace }}
  labels:
    app: license
spec:
  replicas: 1
  selector:
    matchLabels:
      app: license
  template:
    metadata:
      labels:
        app: license
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '5110'
    spec:
      containers:
        - name: license
          image: {{ .Values.image.repository }}/cloud-license{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 5110
            - name: grpc
              containerPort: 5010
          readinessProbe:
            exec:
              command:
                - /usr/bin/healthcheck
            initialDelaySeconds: {{ .Values.lumenvox.service.startDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          {{- if .Values.lumenvox.service.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
                - /usr/bin/healthcheck
            initialDelaySeconds: {{ .Values.lumenvox.service.startDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          {{- end }}
          startupProbe:
            exec:
              command:
                - /usr/bin/healthcheck
            # 4 * 5 = 20 seconds of initial startup time allowed
            failureThreshold: 4
            periodSeconds: {{ .Values.probes.periodSeconds }}
          env:
            - name: DEPLOYMENT_DB_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: lumenvox-configmap
                  key: ConnectionStrings__PostgresConnection
            {{ if .Values.licensing.showDebugOutput }}
            - name: SHOW_DEBUG_OUTPUT
              value: '{{ .Values.licensing.showDebugOutput }}'
            {{- end }}
            - name: LICENSE_CLUSTER_GUID
              value: '{{ .Values.licensing.clusterGuid }}'
            {{- if .Values.licensing.databaseHostOverride }}
            - name: DB_HOST_OVERRIDE
              value: '{{ .Values.licensing.databaseHostOverride }}'
            {{- end }}
            {{- if .Values.licensing.reportEndpoint }}
            - name: LICENSE_REPORT_ENDPOINT
              value: '{{ .Values.licensing.reportEndpoint }}'
            {{- end }}
            - name: LICENSE_REPORT_FREQUENCY_MINS
              value: '{{ .Values.licensing.reportFreqMins }}'
            - name: LICENSE_REPORT_SYNC_HOUR
              value: '{{ .Values.licensing.reportSyncHour }}'
            - name: LICENSE_REPORT_SYNC_MIN
              value: '{{ .Values.licensing.reportSyncMin }}'
            - name: VERBOSE_DB_LOGGING
              value: '{{ .Values.licensing.verboseDbLogging }}'
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
