apiVersion: v1
kind: ConfigMap
metadata:
  name: lumenvox-configmap
  namespace: {{ default .Release.Namespace .Values.defaultNamespace }}
data:
  ConnectionStrings__PostgresConnection: 'Server={{ .Values.postgresql.connection.url }};Port={{ .Values.postgresql.connection.port }};User ID={{ .Values.postgresql.connection.user }};Password={{ .Values.postgresql.connection.password }};Database=aether_deployment_db;Integrated Security=true;Pooling=true;'
  DbSettings__PostgresConnectionString:  'Server={{ .Values.postgresql.connection.url }};Port={{ .Values.postgresql.connection.port }};User ID={{ .Values.postgresql.connection.user }};Password={{ .Values.postgresql.connection.password }};Database=aether_deployment_db;Integrated Security=true;Pooling=true;'
  DbSettings__CommandTimeoutSeconds: '{{ .Values.postgresql.commandTimeoutSeconds }}'
  ASPNETCORE_ENVIRONMENT: 'Production'
  MOCK_TEST_DATA: '{{ .Values.mockData.testDataString }}'
  ServiceAddresses__DeploymentService: 'http://deployment-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  ServiceAddresses__VoiceVerifierService: 'http://voice-verifier-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  ServiceAddresses__EngineResourceService: 'http://engineresource-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  ServiceAddresses__ConfigurationService: 'http://configuration-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  ServiceAddresses__AssureVbs: 'http://assure-vbs-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  ServiceAddresses__AssureIdentityService: 'http://assure-identity-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  ServiceAddresses__LicenseService: 'http://license-service.{{ default .Release.Namespace .Values.defaultNamespace }}:5010'
  ServiceAddresses__BinaryStorageService: 'http://binarystorage-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  ServiceAddresses__TransactionService: 'http://transaction-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  ServiceAddresses__AuditService: 'http://audit-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  ServiceAddresses__ReportingService: 'http://reporting-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  ServiceAddresses__ReportingApiService: 'http://reporting-api-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  ServiceAddresses__ManagementApiService: 'http://management-api-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  DOCKER_REGISTRY: '{{ .Values.image.repository }}'
  COMPOSE_PROJECT_NAME: '{{ .Values.composeProjectName }}'
  DEPLOYMENT_POSTGRES_CONNECTION_STRING: 'Server={{ .Values.postgresql.connection.url }};Port={{ .Values.postgresql.connection.port }};User ID={{ .Values.postgresql.connection.user }};Password={{ .Values.postgresql.connection.password }};Database=aether_deployment_db;Integrated Security=true;Pooling=true;'
  DASHBOARD_POSTGRES_CONNECTION_STRING: 'Server={{ .Values.postgresql.connection.url }};Port={{ .Values.postgresql.connection.port }};User ID={{ .Values.postgresql.connection.user }};Password={{ .Values.postgresql.connection.password }};Database=aether_dashboard_db;Integrated Security=true;Pooling=true;'
  RABBIT_MQ_CONNECTION_STRING: 'amqp://{{ .Values.rabbitmq.connection.user }}:{{ .Values.rabbitmq.connection.password }}@{{ .Values.rabbitmq.connection.url }}:{{ .Values.rabbitmq.connection.port }}'
  DB_USER_COMMON: '{{ .Values.postgresql.user }}'
  DB_PASS_COMMON: '{{ .Values.postgresql.password }}'
  POSTGRES_DB: '{{ .Values.postgresql.postgresDb }}'
  EncryptionSettings__UseEncryption: '{{ .Values.encryption.useEncryption }}'
  EncryptionSettings__MasterKeyProvider: '{{ .Values.encryption.masterKeyProvider }}'
  EncryptionSettings__MasterKey: '{{ .Values.encryption.masterEncryptionKey }}'
  WEB_USER_COMMON: '{{ .Values.web.commonUser }}'
  WEB_PASS_COMMON: '{{ .Values.web.commonPass }}'
  AETHER_ENV_SERVICE_START_DELAY_SECONDS: '{{ .Values.lumenvox.service.startDelaySeconds }}'
  AETHER_RUN_DATABASE_MIGRATIONS: '{{ .Values.postgresql.runMigrations }}'
  AETHER_EXIT_AFTER_DATABASE_MIGRATIONS: '{{ .Values.postgresql.exitAfterMigrations }}'
  ENABLE_ELASTICSEARCH: '{{ .Values.logging.enableElasticsearch }}'
  SERILOG_DEFAULT_LOGGING_LEVEL: '{{ .Values.logging.defaultLevel }}'
  SERILOG_OVERRIDE_MICROSOFT_LOGGING_LEVEL: '{{ .Values.logging.overrideMicrosoftLevel }}'
  SERILOG_OVERRIDE_SYSTEM_LOGGING_LEVEL: '{{ .Values.logging.overrideSystemLevel }}'
  SERILOG_OVERRIDE_GRPC_LOGGING_LEVEL: '{{ .Values.logging.overrideGrpcLevel }}'
  Audit: '{{ .Values.enableAudit }}'
  MASTER_ENCRYPTION_KEY: '{{ .Values.encryption.masterEncryptionKey }}'
  MockDataSettings__DeploymentsJson: '{{ .Values.mockData.deployments }}'
  MockDataSettings__DefaultDeploymentsJson: '{{ .Values.mockData.defaultDeployments }}'
  MockDataSettings__MasterKeysJson: '{{ .Values.mockData.jsonKeys.master }}'
  MockDataSettings__CustomerKeysJson: '{{ .Values.mockData.jsonKeys.customer }}'
  MockDataSettings__EmergencyPublicKeysJson: '{{ .Values.mockData.jsonKeys.emergencyPublic }}'
  DEPLOYMENT_DB_CONNECTION_TIMEOUT_SECONDS: '{{ .Values.postgresql.commandTimeoutSeconds }}'
